"""empty message

Revision ID: d714347c73c0
Revises: 0466510d3464
Create Date: 2025-05-23 07:35:46.675823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd714347c73c0'
down_revision = '0466510d3464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('reportingComment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('reportingComment')
        batch_op.drop_column('reported')

    # ### end Alembic commands ###
